### PR TITLE
Added tooltips

### LINKED ISSUE #2: Provide a Tooltip for the disabled options
image

A tooltip will help end users to understand why certain items are disabled.

### PR DESCRIPTION
**Pull request by TheaAleksovDev**

### CODE REVIEW

**Comment by valentin-aleksandrov** [comment]
I'm OK with this PR.
@TheaAleksovDev could you fix the merge conflicts? I think it would best if you can merge the the PRs before resolving this one.

Tea, if you're up to it, I would **challenge** you to apply that pattern I've showed you with cherry-picking.

### End goal
This PR to have a single commit, which is:
image

### Expectation 
1. Merge the other PRs
     - [Fix hover effect on transactions](https://github.com/TheaAleksovDev/budgetCalculator/pull/5)
     - [REST Polling Implementation](https://github.com/TheaAleksovDev/budgetCalculator/pull/7)
2. Go to main and pull
3. Create a new branch
4. Cherry-pick the needed commit 
5. Delete the `issue-2` branch.
6. Create a new `issue-2` branch.
7. Force push it.

I'm available if you need guidelines.

**Comment by valentin-aleksandrov** [comment]
Awesome job, Tea!

One last thing:
Could you use a present simple tense for the commit message?

**Comment by TheaAleksovDev** [comment]
confused-dog

**Comment by TheaAleksovDev** [comment]
giphy

**Review by valentin-aleksandrov — APPROVED** [review]

**Pull request merged**
